---
Name: csp_configuration
---
# default policy configuration
NSWDPC\Utilities\ContentSecurityPolicy\Policy:
  nonce_length: 16
  # or 'middleware'
  nonce_injection_method: 'requirements'
  run_in_modeladmin: false
  max_age: 3600
  include_subdomains: true
  whitelisted_controllers: []
NSWDPC\Utilities\ContentSecurityPolicy\ReportingEndpoint:
  # by default, do not accept local reports
  accept_reports: false
# report removal job
NSWDPC\Utilities\ContentSecurityPolicy\PruneViolationReportsJob:
  older_than: 1
---
Name: csp_extensions
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\SiteTreeExtension
SilverStripe\Control\Controller:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\ControllerExtension
SilverStripe\Security\Security:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\ContentSecurityPolicyEnable
